name: Tests
on: push
env:
  CORESIGNAL_API_KEY: ${{ secrets.CORESIGNAL_API_KEY }}
  WH_ACCOUNT_PASSWORD: ${{ secrets.WH_ACCOUNT_PASSWORD }}
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Run Python ${{ matrix.python-version }} Tests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install -r  reqs.txt
    - run: pytest tests
